

#
# Makefile Projet C++
#
# Pour générer un petit programme de test
#

# Compilateur
CC=g++
CFLAGS=-Wall --std=c++11 -g

# Objets 
SRC=main.cpp
OBJS=$(SRC:.cpp=.o)


# Executable
TEST_PATH=./test/
TEST_EXE=test-framework

# Bibliothèque
LIB_TARGET=libDiderot.a


.PHONY : clean clear $(LIB_TARGET)

all: $(TEST_EXE)

$(TEST_EXE): $(OBJS) $(LIB_TARGET)
	@echo " = "$@" - Edition de lien "
	@$(CC) -o $@ $(OBJS) $(LIB_TARGET) $(CFLAGS)


#
# Objet principal
#

main.o: $(TEST_PATH)main.cpp
	@echo " = Compiler "$<" vers "$@
	@$(CC) -c -o $@ $< $(CFLAGS)


#
# Netoyage
#


clean:
	@echo " = Supprimer les fichiers intermédaires"
	@rm -f *.o

clear: clean
	@echo " = Nettoyage du repertoire "$(TEST_PATH)
	@rm -f $(TEST_EXE)


