

#
# Makefile Projet C++
#
# Pour générer un petit programme de test
#

# Compilateur
CC=g++
CFLAGS=-Wall --std=c++0x -g

# Objets 
SRC=main.cpp
OBJS=$(SRC:.cpp=.o)


# Executable
TEST_PATH=./test/
EXE=test-framework

# Bibliothèque
LIB_TARGET=libDiderot.a


all: $(EXE)

$(EXE): $(OBJS) $(LIB_TARGET)
	$(CC) -o $@ $(OBJS) $(LIB_TARGET) $(CFLAGS)


#
# Objet principal
#

main.o: $(TEST_PATH)main.cpp
	$(CC) -c -o $@ $< $(CFLAGS)


#
# Netoyage
#

.PHONY : clean clear

clean:
	rm -f *.o

clear: clean
	rm -f $(EXE)

